import os
import sys
import numpy as np

# Add the parent directory to sys.path so we can import the app module
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from app.embeddings import embed_documents, embed_query

def cosine_similarity(vec_a, vec_b):
    """Calculates the cosine similarity between two vectors."""
    a = np.array(vec_a)
    b = np.array(vec_b)
    # Cosine Similarity = (A dot B) / (||A|| * ||B||)
    dot_product = np.dot(a, b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    return dot_product / (norm_a * norm_b)

def test_embeddings():
    print("Loading embedding model (this might take a few seconds on the first run)...")
    
    # 1. Setup mock chunks
    mock_chunks = [
        {"chunk_id": "c1", "text": "This is a test document.", "source": "test.txt", "page_number": 1},
        {"chunk_id": "c2", "text": "This is another test.", "source": "test.txt", "page_number": 1}
    ]
    
    # 2. Embed the documents
    embedded_chunks = embed_documents(mock_chunks)
    
    # Verify embeddings are generated and metadata is preserved
    assert len(embedded_chunks) == 2, "Expected 2 chunks back."
    assert "embedding" in embedded_chunks[0], "Embedding key is missing."
    assert embedded_chunks[0]["chunk_id"] == "c1", "Metadata was lost."
    
    dim = len(embedded_chunks[0]["embedding"])
    print(f"Embedding dimension generated by the model: {dim}")
    assert dim > 0, "Embedding dimension should be greater than 0."
    assert len(embedded_chunks[1]["embedding"]) == dim, "Dimension inconsistency between chunks."
    
    # 3. Embed a query and check dimensions
    query_emb = embed_query("test query")
    assert len(query_emb) == dim, "Query dimension does not match document dimension."
    
    # 4. Verify same input produces a consistent embedding
    q1 = embed_query("same text")
    q2 = embed_query("same text")
    assert np.allclose(q1, q2), "Embeddings are not deterministic!"

    print("\nAll basic embedding tests passed!")

    # 5. Semantic Similarity Experiment
    print("\n--- Semantic Similarity Experiment ---")
    sentence_A = "Machine learning models learn patterns from data."
    sentence_B = "Algorithms can identify patterns by training on historical examples."
    sentence_C = "Pizza is usually made with cheese and tomato sauce."
    
    print(f"Sentence A: {sentence_A}")
    print(f"Sentence B: {sentence_B}")
    print(f"Sentence C: {sentence_C}")
    
    # Generate embeddings
    emb_A = embed_query(sentence_A)
    emb_B = embed_query(sentence_B)
    emb_C = embed_query(sentence_C)
    
    # Calculate similarities
    sim_AB = cosine_similarity(emb_A, emb_B)
    sim_AC = cosine_similarity(emb_A, emb_C)
    
    print(f"\nCosine Similarity (A and B): {sim_AB:.4f}")
    print(f"Cosine Similarity (A and C): {sim_AC:.4f}")
    
    assert sim_AB > sim_AC, "Semantic similarity logic failed!"
    print("\nSuccess! Sentences A and B are mathematically closer than A and C.")

if __name__ == "__main__":
    test_embeddings()
